database:
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "aesthetics"

smtp:
  password: "djlp sdau zhil kutb"
  from: "aesthetics.team.contacts@gmail.com"
  host: "smtp.gmail.com"
  port: "587"

redis:
  host: "localhost:"
  port: "6379"
  password: ""
  db: "0"

twilio:
  accountSID: "ACa49147561f645b57397f143eddf45f06"
  authToken: "f6c3d5cb4e9e14261e5e520cbd5d2b07"
  twilioNumber: "+15707474327"

dropbox:
  token: "sl.u.AFrkbNsK1K91jpsZGwKZJ5UkkSJVeNqbashX_bpyj0HjispYcnp7JSs4MfgbAqILMgCeVM59bzEicZMP6y9T3Tuau39vTudsQSPek6q5h5Zif6Rr8tLW5VXIqhfvAowTAW-HS6gJBjsM54af4jEF0il2DXCY_AyZOowPTqtAkettZOJrPvQQ6Ul2JeKE6oB-hue8aWoOk20L7ek4Yvy2aX7lB2oqLLEJIOCn0l4VFOuFGy_mnv10LN04Jz8JMdpOqWNYiunafmr_WUCH0F7T_JGjClfHBf5ExRwvLHY4LQnzGwZW6u5gY-XYT3E9iL2LDcOvi2HrssjFvcKsNeDgYMvDENryFQMGs_qAgyfKvgD-t2janDTXQin5LepLViIxYd-d88kmcZutnlSqI4e132b2GmsogIWKwYiO_luDToV3NnZnylwfV5U7bXM75faLphyZ5HFK9P3MeyNdmibUEitol7CtJRfw_Y40l81cUbNAjFyQ9n7-j4K9rS43G-y4MbDqBg1vLAr2ujRx23oRhkBVsNTcNrFTugrA-Ize_xMjzoThRPy9i038b1z2AjMKvtheAbilIIlcqHrOgmhA0RsIFHx311MEs8kLW5S7eJyaXSMUOFOibc2C-G4qqdwclYbTh01krTgLsiqjnmTu58avasiufvknbgAoyp3rRkxj0mNxm4z3Nm8e_dcVwUGRFKTE9pa6KRb_QLAA-zbXaTKxy-W36iIOTjB3JiXw_3Bi4HlAz5bIJ749-rIFlmv4kzo61rrEOXFD9txMvJhFvQLp9VqRYslbqix5IYj-JC0w807RfA_2vEmcKtrh4KLB2FpL0D6gsl3LZ2P76yewXz2EDJt1qDvNF3mx1ZbDBGzDFOsDQig0OeNksxR2khQn9AKxZxy5brIkm6grCoBeuzYNhlGrFV7l2mmJ2vWK3TJr1edDL9T3ga51109g9TXu13wfL_jDhSLdvya9ILOiLa_bn0OlzT_XC9XNP90LqecvwJc0vXESUDEADqx57_8iP9mlW4AVk9iHXfrqP63vqDdfHyqlTFwx5C_mO3MozW8Gihh4D9Gh0cY6q_m5YvlJeyGSkQukLM8UvKfrsvpgUKhIhdlevxUOKjhwCvGaChG5aMlD3oavP8aUbyaxECCCsr5oRN_1PJ09vflRS5-GdDlWOr55Cg-ZqXbeH0_Gi4M309Wsnj4OmTntHHJrDyzUNFVh4b1N2Rt7gFzXKCms5Fl4KMqdQ2qug2_wAJ5XwA-pfisx0EvtNvjM-RN0eVp88b9nfEZidMobDRMJxcU58lbAcVQ_UpGnBi7Ub5RnW9FcPTs7cKsIoTUPpjWrYQgme5jFbByF3KUcoyBCzNueSQ9K5thrboUkumaxQqQ6fbtARZ4iInpii-vhQUnwaWqQH0ciWz41VBVGYkss6rneF1KkJexfCVIO7Nx0-uGUTcIbiw"